mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.example.test.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.45.61.136:3306/authority_management?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
   redis:
     host: localhost
     port: 6379
redis:
server:
  port: 8001

